### User Registration Test-1
POST http://localhost:8080/api/auth/registar
Content-Type: application/json

{
  "username": "mehedi",
  "email": "mehedi@gmail.com",
  "password": "123324",
  "role": "USER",
  "countyId": "BD"
}


### User Login Test
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "mehedi@gmail.com",
  "password": "123324"
}


### Holtel Test
POST http://localhost:8080/api/hotels/add
Content-Type: application/json

{
  "vendor": { "id": 1 },
  "destination": { "id": 1 },
  "hotelName": "Radisson Blu",
  "address": "Dhaka",
  "status": "ACTIVE",
  "descriptions": "Five star hotel"

}


### Room Test
POST http://localhost:8080/api/rooms/add
Content-Type: application/json

{
  "roomTypeName": "Deluxe King",
  "amenities": "WiFi, AC, TV, Mini Bar",
  "pricePerNight": 5000.0,
  "availableQuantities": 10,
  "status": "AVAILABLE",
  "hotel": { "id": 1 }
}


### Destination Test
POST http://localhost:8080/api/desination/add
Content-Type: application/json

{
  "name": "Cox's Bazar",
  "region": "Chittagong",
  "description": "The longest natural sandy beach in the world, famous for its scenic beauty and sunsets.",
  "isAlive": true
}


### Chat history Test
POST http://localhost:8080/api/chat/history/add
Content-Type: application/json

{
  "user": {
    "id": 1
  },
  "userInput": "Cox's Bazar-e thakar shera hotel konta?",
  "aiResponse": "Cox's Bazar-e thakar jonno Sayeman Beach Resort ba Sayeman Heritage bhalo hote pare.",
  "sessionId": "session_abc_123"
}


###Booking Test
POST http://localhost:8080/api/booking/add
Content-Type: application/json

{
  "user": {
    "id": 1
  },
  "hotel": {
    "id": 1
  },
  "room": {
    "id": 1
  },
  "checkInDate": "2026-04-10",
  "checkOutDate": "2026-04-15",
  "guestCount": 2,
  "totalPrice": 15000.50,
  "status": "PENDING",
  "specialRequest": "Please provide a room with a sea view and an extra pillow."
}

### Transport Test
POST http://localhost:8080/api/transports/add
Content-Type: application/json

{
  "origin": {
    "id": 1
  },
  "destination": {
    "id": 1
  },
  "model": "Hino 1J (Non-AC)",
  "operatorName": "Hanif Enterprise",
  "estimatedCost": 850.0,
  "estimatedDuration": "12 hours",
  "frequency": "Daily (Every 1 hour)",
  "isLocal": false
}

### Transport Test
POST http://localhost:8080/api/transports/add
Content-Type: application/json

{
  "origin": {
    "id": 1
  },
  "destination": {
    "id": 1
  },
  "model": "Hino 1J (Non-AC)",
  "operatorName": "Hanif Enterprise",
  "estimatedCost": 850.0,
  "estimatedDuration": "12 hours",
  "frequency": "Daily (Every 1 hour)",
  "isLocal": false
}